-- SET @@global.sql_mode= 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
USE `GameSingle`;

SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE 'names.csv'
INTO TABLE User
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES (ID, Name);

LOAD DATA LOCAL INFILE 'owners.csv'
INTO TABLE Owner
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
IGNORE 1 LINES (OwnerID, GameID);

SET FOREIGN_KEY_CHECKS = 1;
