USE `GameSingle`;

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE tmp_data SELECT * FROM Game;
TRUNCATE TABLE Game;
ALTER TABLE Game ADD PRIMARY KEY (ID);
INSERT IGNORE INTO Game SELECT * from tmp_data;
DROP TABLE tmp_data;

CREATE TABLE IF NOT EXISTS User (
  `ID` varchar(255) NOT NULL,
  `Name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS Owner (
  `OwnerID` varchar(255) NOT NULL,
  `GameID` varchar(255) NOT NULL,
  PRIMARY KEY (OwnerID,GameID),
  FOREIGN KEY (OwnerID) REFERENCES User(ID),
  FOREIGN KEY (GameID) REFERENCES Game(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS Image(
  `ID` varchar(255) NOT NULL,
  `HeaderImage` LONGBLOB DEFAULT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID) REFERENCES Game(ID)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

SET FOREIGN_KEY_CHECKS = 1;
